name: "Wheelhouse"

on:
  workflow_dispatch:
  push:
    branches:
      - "trunk"
    paths:
      - ".github/workflows/create-wheelhouse.yml"

jobs:
  wheelhouse:
    runs-on: "ubuntu-latest"
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5" # v4

      - name: "Create wheelhouse"
        run: |
          mkdir -p _site/discord-ext-songbird
          touch _site/.nojekyll
          GENERATED_TIME=$(TZ=UTC date "+%Y-%m-%dT%H:%M:%SZ")
          cat <<EOF > _site/index.html
          <!DOCTYPE html>
          <html>
              <head>
                  <meta name="pypi:repository-version" content="1.4">
                  <title>Simple index for https://github.com/beer-psi/discord-ext-songbird</title>
              </head>
              <body>
                  <h1>Simple index for https://github.com/beer-psi/discord-ext-songbird</h1>
                  <p>Generated on <time datetime="$GENERATED_TIME">$GENERATED_TIME</time>.</p>
                  <a href="discord-ext-songbird/">discord-ext-songbird</a>
              </body>
          </html>
          EOF

      # While I'd love to quote every YAML string ever, this one stays unquoted because Zed
      # has specific syntax highlighting for github-script for whatever reason.
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const fs = require("fs");
            const { data: releases } = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo,
            });
            const tags = [];

            for (const release of releases) {
                if (release.draft) {
                    continue;
                }

                for (const asset of release.assets) {
                    if (!asset.name.endsWith(".whl") && !asset.name.endsWith(".tar.gz")) {
                        continue;
                    }

                    tags.push(`<a href="${asset.browser_download_url}#${asset.digest.replace(":", "=")}">${asset.name}</a><br />`);
                }
            }

            const latestVersion = releases.sort((a, b) => new Date(b.created_at).valueOf() - new Date(a.created_at).valueOf())[0].tag_name.replace(/^v/u, "");
            const generatedDate = new Date().toISOString();

            fs.writeFileSync(
                "_site/discord-ext-songbird/index.html",
                `
            <!doctype html>
            <html>
                <head>
                    <meta name="pypi:repository-version" content="1.4">
                    <meta name="pypi:project-status" content="active">
                    <title>Links for discord-ext-songbird</title>
                </head>
                <body>
                    <h1>Links for discord-ext-songbird</h1>
                    <p>
                        Latest version:
                        <input
                            type="text"
                            value="${latestVersion}"
                            id="requirement"
                            style="font-family: monospace; width: ${latestVersion.length}ch;"
                            readonly="readonly"
                        />
                    </p>
                    <p>Generated at <time datetime="${generatedDate}">${generatedDate}</time>.</p>
                    ${tags.join("\n")}
                    <script>
                        document.getElementById('requirement').onfocus = (e) => e.target.select();
                    </script>
                </body>
            </html>
            `
            );

      - uses: "actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b" # v4
        with:
          path: "_site/"

  deploy:
    needs: "wheelhouse"
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e" # v4
        id: "deployment"
