name: "Verify MSRV"

on:
  push:
    paths-ignore:
      - ".github/workflows/CI.yml"
      - ".github/workflows/create-wheelhouse.yml"
  pull_request:
  workflow_dispatch:

jobs:
  msrv:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6

      - name: "Verify MSRV"
        uses: |
          cargo install cargo-msrv
          cargo msrv verify
